plugins:
  layouts_enabled:
    client: true
    default: true
  layouts_sidebar_left_width:
    client: true
    default: 250
  layouts_sidebar_right_width:
    client: true
    default: 250
  layouts_sidebar_left_fixed:
    client: true
    default: true
  layouts_sidebar_right_fixed:
    client: true
    default: true
  layouts_sidebar_left_can_hide:
    client: true
    type: list
    default: ''
    choices:
      - Topic List
      - Topic
      - Profile
      - Tags
  layouts_sidebar_right_can_hide:
    client: true
    type: list
    default: ''
    choices:
      - Topic List
      - Topic
      - Profile
      - Tags
  layouts_sidebar_responsive_threshold:
    client: true
    default: 850
  layouts_mobile_enabled:
    client: true
    default: false
  layouts_mobile_menu:
    client: true
    type: list
    default: ''
